### ISSUE TITLE
Sugestão: indice de satisfação

### ISSUE THREAD

**Issue by mtmello2003** [rafaelcruzpb/Impressora3DBrasil#2]
Realmente ótima idéia reunir uma lista ativa e colaborativa de fornecedores porém, quando abri a lista, minha primeira dúvida foi: vale a pena arriscar e comprar deste fornecedor X?

Então me veio a idéia de que se ao lado de cada um, tiver uma especie de indice de satisfação, com por exemplo a qtd de pessoas que falam bem / quantidade de pessoas que falam mal do fila deste fornecedor, seria algo que pudesse já dar um norte na tomada de decisão...

Exemplo:
Loja XXXXXXX3d.com B5 / R3 (Boa experiência 5 usuários / Ruim exeperiência 3).
Loja YYYYYYY3d.com B9 / R0 (esta está super bem cotada!).

**Comment by Gustavo-Murad** [comment]
É uma ótima ideia, estamos bolando um jeito correto de fazer isso.

Eu já havia chegado a pensar nisso desde o começo mas acho que "opinião de usuário" é um negócio meio complicado, depois que vi que tem gente que paga "bot" para dar "deslike" em canal de conteúdo 3D dos outros eu acredito que pagar para usuários/bots fazerem review positivo ou votar é o que mais pode (e já deve) acontecer. Então tem que pensar em uma forma de fazer isso sem que se aproveitem do projeto pra divulgar ou fazer marketing de loja!

**Comment by rafaelcruzpb** [comment]
Interessante a ideia, mas acredito que controlar isso seria um tanto complicado, porque ser uma boa experiência ou não, é relativo... pessoas poderiam alterar esses índices com valores falsos, poderia ser o próprio dono da loja para tentar alavancar o seu indice. Uma alternativa que poderia se pensar, seria colocar o link para a pagina da loja no reclameaqui, que o pessoal poderiam verificar a reputação do lojista de forma facil.
