### ISSUE TITLE
A lista de filamentos deveriam ter notas

### ISSUE THREAD

**Issue by willsoares** [rafaelcruzpb/Impressora3DBrasil#6]
Existem muitos fornecedores, os filamentos deveriam ter algum conceito de nota ou coisa parecida.

**Comment by WagnerTT** [comment]
Concordo que seria algo interessante, mas é uma questão pessoal.
As notas seriam baseadas em que?
O que pode ser bom para você as vezes não é bom para outros e vice e versa.
É algo a ser pensado e discutido, se fizer sentido creio que pode ser aplicado.

**Comment by willsoares** [comment]
Não tem problema ser algo baseado em opinião, mas caso seja, poderia ter um valor de 1-5 pra indicar algumas propriedades, tipo, consistência(chance de uma impressão falhar por causa do filamento), cor(representação da cor prometida vs cor alcançada), preço, preferência da comunidade.

Podia ter um formulário pro pessoal ir preenchendo e completar a tabela. Se possível, ir mostrando exemplos desse filamento

**Comment by Gustavo-Murad** [comment]
@willsoares e @SmithnTT , o maior problema nem é esse... já vi fornecedor de filamento, youtuber da área de impressão 3D, grupo de facebook da área do 3D ser "atacado" por bots ou ter positivações bem estranhas em suas páginas.

Não duvido nem um pouco que um vendedor posso contratar bots, ou mesmo colocar colaboradores para votar favoravelmente na marca dele só pra "subir" no ranking caso façamos um!

Essa sim é minha maior preocupação no tema, se alguém tiver alguma sugestão para combater isso acredito que facilite bastante pra coisa toda acontecer.

**Comment by rafaelcruzpb** [comment]
Agradeço a sugestão, mas como foi discutido, atualizar esses valores seria complicado, pois estaria aberto para qualificações falsas e outros fatores. Se vocês encontrarem alguma ferramenta que facilite a aplicação dessa ideia e que seja possível anexar aqui, só reabrir a _issue_ e sugerir.
